export const siteSettings = {
  name: "siteSettings",
  title: "Site Settings",
  type: "document",
  fields: [
    { name: "siteName", title: "Site Name", type: "string" },
    { name: "tagline", title: "Tagline", type: "string" },
    { name: "description", title: "Site Description (SEO)", type: "text", rows: 2 },
    { name: "phone", title: "Phone Number", type: "string" },
    { name: "email", title: "Email", type: "string" },
    { name: "address", title: "Address", type: "text", rows: 2 },
    { name: "whatsappNumber", title: "WhatsApp Number (with country code)", type: "string" },
    { name: "whatsappMessage", title: "WhatsApp Default Message", type: "string" },
    { name: "googleMapsEmbed", title: "Google Maps Embed URL", type: "url" },
    { name: "businessHours", title: "Business Hours", type: "text", rows: 3 },
    {
      name: "heroImage",
      title: "Homepage Hero Image",
      type: "image",
      options: { hotspot: true },
      description: "Main hero image for the homepage (recommended: 1920x1080px)",
    },
    {
      name: "ogImage",
      title: "Social Share Image (Open Graph)",
      type: "image",
      description: "Image shown when sharing on social media (recommended: 1200x630px)",
    },
  ],
};
